### ISSUE TITLE
Implement destruction list creation for the record manager

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/record-management-app#6]
A record manager is responsible for the creation of destruction lists. The record manager has the knowledge to "plan" the process that happens after creation.

For the record manager, it's important that they can select the cases in an efficient way that are to be destroyed. After creation, the list is "sent" to other roles for review.

The creation page must minimally provide:

- data filters
- a presentation of data matching the filters
- the option to "freeze" this list into a collection for destruction

The below wireframes give an impression of these core elements, a more detailed description is found below.

![image](https://user-images.githubusercontent.com/5518550/83761879-2e84de00-a677-11ea-8d7e-b64b0eb5d78a.png)

---

## Filters

The following filters should be available (and none of them are required). Combining filters works in an AND fashion - they reduce the result set further on top of each other.

- zaaktypen: a multi-select of available zaaktypen in the configured catalogi API(s). Record managers should be able to select a subset of zaaktypen (one or more), and only see zaken belonging to those zaaktypen.
- start date: should filter zaken on `startdatum__gte` - only include zaken started on or after the selected date
- end date: should filter zaken on `einddatum__gte` - only include zaken finished on or after the selected date (@JurjenBert  - is this right?)

The `resultaten` filter in the wireframes can be left out. The `Action` radio select should be present, but disabled (as we currently only implement destruction and not transfer of records).

## Cases list

The main panel shows the list of zaken matching the selection criteria. The displayed columns should default to "omschrijving", "zaaktype", "startdatum", "einddatum" and "archiefactiedatum". The end-user should be able to configure which columns to display (nice to have).

Cases must _always_ be limited to cases where the `archiefactiedatum` is in the past (or current date), and have `archiefnominatie=vernietigen`.

Every row represents a single zaak. There is a checkbox to include the zaak on the list for every zaak. The table header should have a checkbox for "select-all" functionality.

When clicking a zaak-row, detail information should be shown, but **only** if the user-role has `can_view_case_details`

A case can only be on a single list - this means that if any other lists have the case as `scheduled`, it should be presented in the result list as "grayed out"/disabled.

## the option to "freeze" this list into a collection for destruction

Currently this is represented in a button in the top right, showing a count of the zaken, but this should be made more accessible/explicit.

Clicking this button then brings up the interface to "finalize" the destruction list.

![image](https://user-images.githubusercontent.com/5518550/83765893-051a8100-a67c-11ea-88f1-40b9a7a34716.png)

- It should show how many cases are included
- It must have a form field to give a name
- it must have the ability to assign reviewers - the record manager knows _who_ those should be
    - reviewers are added by selecting a user
    - the order of reviewers is important
    - for each selected reviewer, their assigned role (`Role` model) should be displayed

A confirmation button then causes this data to persist and the process to start.

---

## Side effects

- When a list is created, a notification should be sent to the next assignee (=first reviewer). This should be a notification in their notifs. area AND an e-mail to the user with a link to the review page for that particular list.

- audit records should be created in django-timeline-logger that log the creation of the list. additionally, the list of zaak-urls included should probably be logged in the `extra_data` as well

---

## Technical considerations

This page is highly dynamic in user-interaction, so it will probably make sense to set up own API-endpoints and implement the bulk of the page with React (components). This also allows us to re-use some components from the NLX team (@sergei-maertens follow up)

**Comment by JurjenBert** [comment]
In response to the question above (should filter zaken on einddatum__gte - only include zaken finished on or after the selected date (@JurjenBert - is this right?). Yes, only zaken finished on or after the selected dat should be included in the search results.

**Comment by JurjenBert** [comment]
@sergei-maertens As a record manager I would eventually like to see more columns than the ones in the wireframes. We talked about possible columns to be shown last week (ie. zaaknummer, Zaaktype,  Resultaat, Selectielijstcategorie, Archiefactiedatum, Reden wijziging, Datum uitvoering, Log, Relatie, Omschrijving, Einddatum). Not all these columns are relevent and certainly not in a MVP. 

Should i punt the addionional columns in a seperate user story? 

For future development we should also think about destruction in the context of hoofdzaken en bijdrage zaken, and showing the reason why archivedata has been changed in the past (if that situation occurs). Same question here: user stories? I could also put them in the ZGW repository for the time being.

**Comment by sergei-maertens** [comment]
@JurjenBert 

> Should i punt the addionional columns in a seperate user story?

Yes, please do! We're keeping it out of the current project then for now and go with a set of defaults. There is a remark already in this issue that the wireframe-columns are outdated, and going with a hardcoded set for now is easy enough.

> For future development we should also think about destruction in the context of hoofdzaken en bijdrage zaken, and showing the reason why archivedata has been changed in the past (if that situation occurs). Same question here: user stories? I could also put them in the ZGW repository for the time being.

User stories are good, yes. Either repo is fine for me - you decide what works best for you.
